In [23]:
import pandas as pd
import numpy as np
#import import_ipynb
#import data_cleaning another way of loading an existing file inside this jupyter notebook.

In [2]:
train_clean = pd.read_csv('./output/train_clean.csv', index_col="id")

In [3]:
train_clean.head()


carat  cut  color  clarity  depth  table     x  price
id                                                       
0    0.50    5      7        4   62.3   55.0  5.11   1845
1    1.54    2      2        5   63.6   60.0  7.30  10164
2    1.32    3      1        2   61.7   60.0  6.95   5513
3    1.20    5      2        3   62.1   55.0  6.83   5174
4    1.73    4      2        3   61.2   60.0  7.67  10957

# Modeling, Prediction, and Evaluation

We'll start off this section by splitting the data to train and test. Name your 4 variables X_train, X_test, y_train, and y_test. Select 90% of the data for training and 10% for testing.

In [4]:
from sklearn.model_selection import train_test_split


In [5]:
y=train_clean[['price']]
X=train_clean.drop(labels='price', axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.10)

In [6]:
from sklearn.linear_model import LinearRegression

In [7]:
#Definimos el algoritmo a utilizar. Utilizaremos el modelo de LinearRegression. 
#Una vez definido, entrenamos nuestro modelo con los datos correspondientes.
# Para ello, utilizamos la instruccion fit.

lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [8]:
#para calcular la intersección o el valor b
lr.intercept_ 

array([3429.21142454])

In [9]:
# para calcular los valores correspondientes a pendientes.
lr.coef_ 

array([[10816.52454933,   118.12838152,   324.67647161,   503.36001435,
          -85.9741051 ,   -29.83611134,  -877.57925   ]])

In [10]:
#realizamos la prediccion utilizando los datos de prueba X_test
y_pred_test = lr.predict(X_test)
y_pred_train = lr.predict(X_train)

In [11]:
# Procedemos a calcular la precisión del algoritmo, para ello utilizamos la instruccion r2_score.

from sklearn.metrics import r2_score, mean_squared_error
print("R2 for the testing set is: ", r2_score(y_test,y_pred_test))
print("R2 for the training set is: ", r2_score(y_train,y_pred_train))


R2 for the testing set is:  0.9054573682698025
R2 for the training set is:  0.9078501087873497


In [12]:
# Cuanto más cercano a 1 sea el valor R2, mejor será nuestro modelo.

In [13]:
rmse_test = mean_squared_error(y_test, y_pred_test)**0.5
rmse_train = mean_squared_error(y_train, y_pred_train)**0.5

print("Root mean squared error (test): ",rmse_test)
print("Root mean squared error (train): ",rmse_train)


Root mean squared error (test):  1220.7304052343607
Root mean squared error (train):  1218.4675996850913


In [14]:
#Este rmse obtenido de 1220.73 nos indica que los datos obtenidos en algunos casos 
# serán similares, y en otros posiblemente la diferencia sea considerable entre si, 
# por lo tanto, este modelo no es el más adecuado implementar para este conjunto de datos.

In [24]:
# Realizamos el cross validation score
from sklearn.model_selection import cross_val_score
scores = cross_val_score(lr,X,y, cv=10)
print("The accuracy of this model is: ", np.mean(scores))

The accuracy of this model is:  0.9075245420275039


In [15]:
#Cargamos el predict_clean csv que añadirá la columna price a dicho csv.
predict_clean = pd.read_csv('./output/predict_clean.csv', index_col="id")

In [16]:
predict_clean.head()

carat  cut  color  clarity  depth  table     x
id                                                
0    0.45    4      6        3   62.8   58.0  4.88
1    1.23    5      3        3   61.0   56.0  6.96
2    0.33    5      2        8   61.8   55.0  4.46
3    0.51    4      7        4   58.0   60.0  5.29
4    0.40    4      6        4   62.2   59.0  4.71

In [17]:
X_test = predict_clean

In [18]:
y_pred = lr.predict(X_test)
y_pred

array([[ 815.0448723 ],
       [6785.09375934],
       [1397.35021731],
       ...,
       [1885.74958479],
       [-278.66702748],
       [5008.0554759 ]])

In [19]:
predict_clean['price'] = y_pred
predict_clean['price']

id
0         815.044872
1        6785.093759
2        1397.350217
3        2285.268821
4         948.515483
            ...     
13480   -1589.972576
13481    4668.979584
13482    1885.749585
13483    -278.667027
13484    5008.055476
Name: price, Length: 13485, dtype: float64

In [21]:
#predict_clean['price'].to_csv('output/1_linear_regression_test.csv') #to save the generated dataframe in a csv.